#include <sol/sol.hpp>

#include <Core/GlobalLocator.h>
#include <Debug/Log.h>
#include <Scene/SceneManager.h>
#include <Input/KeyCodes.h>
#include <Input/Input.h>

void BindLuaGlobal(sol::state& p_state) {

	using namespace Moon;

	p_state.new_enum<Key>("Key", {
		{"SPACE",			Key::Space},
		{"APOSTROPHE",		Key::Apostrophe},
		{"COMMA",			Key::Comma},
		{"MINUS",			Key::Minus},
		{"PERIOD",			Key::Period},
		{"SLASH",			Key::Slash},
		{"ALPHA_0",			Key::Number_0},
		{"ALPHA_1",			Key::Number_1},
		{"ALPHA_2",			Key::Number_2},
		{"ALPHA_3",			Key::Number_3},
		{"ALPHA_4",			Key::Number_4},
		{"ALPHA_5",			Key::Number_5},
		{"ALPHA_6",			Key::Number_6},
		{"ALPHA_7",			Key::Number_7},
		{"ALPHA_8",			Key::Number_8},
		{"ALPHA_9",			Key::Number_9},
		{"SEMICOLON",		Key::Semicolom},
		{"EQUAL",			Key::Equal},
		{"A",				Key::A},
		{"B",				Key::B},
		{"C",				Key::C},
		{"D",				Key::D},
		{"E",				Key::E},
		{"F",				Key::F},
		{"G",				Key::G},
		{"H",				Key::H},
		{"I",				Key::I},
		{"J",				Key::J},
		{"K",				Key::K},
		{"L",				Key::L},
		{"M",				Key::M},
		{"N",				Key::N},
		{"O",				Key::O},
		{"P",				Key::P},
		{"Q",				Key::Q},
		{"R",				Key::R},
		{"S",				Key::S},
		{"T",				Key::T},
		{"U",				Key::U},
		{"V",				Key::V},
		{"W",				Key::W},
		{"X",				Key::X},
		{"Y",				Key::Y},
		{"Z",				Key::Z},
		{"LEFT_BRACKET",	Key::LeftBracket},
		{"BACKSLASH",		Key::Backslash},
		{"RIGHT_BRACKET",	Key::RightBracket},
		{"GRAVE_ACCENT",	Key::GraveAccent},
		{"WORLD_1",			Key::World_1},
		{"WORLD_2",			Key::World_2},
		{"ESCAPE",			Key::Escape},
		{"ENTER",			Key::Enter},
		{"TAB",				Key::Tab},
		{"BACKSPACE",		Key::Backspace},
		{"INSERT",			Key::Insert},
		{"DELETE",			Key::Delete},
		{"RIGHT",			Key::Right},
		{"LEFT",			Key::Left},
		{"DOWN",			Key::Down},
		{"UP",				Key::Up},
		{"PAGE_UP",			Key::PageUp},
		{"PAGE_DOWN",		Key::PageDown},
		{"HOME",			Key::Home},
		{"END",				Key::End},
		{"CAPS_LOCK",		Key::CapsLock},
		{"SCROLL_LOCK",		Key::ScrollLock},
		{"NUM_LOCK",		Key::NumLock},
		{"PRINT_SCREEN",	Key::PrintScreen},
		{"PAUSE",			Key::Pause},
		{"F1",				Key::F1},
		{"F2",				Key::F2},
		{"F3",				Key::F3},
		{"F4",				Key::F4},
		{"F5",				Key::F5},
		{"F6",				Key::F6},
		{"F7",				Key::F7},
		{"F8",				Key::F8},
		{"F9",				Key::F9},
		{"F10",				Key::F10},
		{"F11",				Key::F11},
		{"F12",				Key::F12},
		{"F13",				Key::F13},
		{"F14",				Key::F14},
		{"F15",				Key::F15},
		{"F16",				Key::F16},
		{"F17",				Key::F17},
		{"F18",				Key::F18},
		{"F19",				Key::F19},
		{"F20",				Key::F20},
		{"F21",				Key::F21},
		{"F22",				Key::F22},
		{"F23",				Key::F23},
		{"F24",				Key::F24},
		{"F25",				Key::F25},
		{"LEFT_SHIFT",		Key::LeftShift},
		{"LEFT_CONTROL",	Key::LeftControl},
		{"LEFT_ALT",		Key::LeftAlt},
		{"LEFT_SUPER",		Key::LeftSuper},
		{"RIGHT_SHIFT",		Key::RightShift},
		{"RIGHT_CONTROL",	Key::RightControl},
		{"RIGHT_ALT",		Key::RightAlt},
		{"RIGHT_SUPER",		Key::RightSuper},
		{"MENU",			Key::Menu}
	});

	p_state.create_named_table("Input",
		"KeyDown", [](Key p_key) { return Input::KeyDown(p_key); },
		"KeyPressed", [](Key p_key) { return Input::KeyPressed(p_key); },
		"GetMouseX", Input::GetMouseX,
		"GetMouseY", Input::GetMouseX,
		"GetMouseXOffset", Input::GetMouseXOffset,
		"GetMouseYOffset", Input::GetMouseYOffset,
		"ShowCursor", Input::ShowCursor,
		"HideCursor", Input::HideCursor,
		"DisableCursor", Input::DisableCursor,
		"LockCursor", Input::LockMouse,
		"LeftMouseDown", Input::LeftMouseDown,
		"RightMouseDown", Input::RightMouseDown,
		"LeftMousePressed", Input::LeftMousePressed,
		"RightMousePressed", Input::RightMousePressed
	);

	p_state.create_named_table("Debug",
		"Log", [](const std::string& message) { HZ_CORE_TRACE(message); },
		"LogInfo", [](const std::string& message) { HZ_CORE_INFO(message); },
		"LogWarning", [](const std::string& message) { HZ_CORE_WARN(message); },
		"LogError", [](const std::string& message) { HZ_CORE_ERROR(message); }
	);

	p_state.create_named_table("SceneManager",
		"GetCurrentScene", []() -> Scene& { return *FTSERVICE(SceneManager).GetCurrentScene(); },
		"Load", [](const std::string& filepath) {}
	);
}