#pragma once

#include "Components/CTransform.h"
#include "Components/CCamera.h"
#include "Components/CModelRenderer.h"
#include "Components/CSkinnedModelRenderer.h"
#include "Components/CMaterialRenderer.h"
#include "Components/CRigidBody.h"
#include "Components/CBoxCollider.h"
#include "Components/CCapsuleCollider.h"
#include "Components/CCharacterController.h"
#include "Components/NetScriptComponent.h"
#include "Components/CPointLight.h"
#include "Components/CDirectionalLight.h"
#include "Components/CAudio.h"
#include "Components/CAudioListener.h"
#include "Components/CPrefab.h"